<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Espaol (Mxico)_home_img_holder</name>
   <tag></tag>
   <elementGuidId>35cc9680-7bfe-4319-be37-eeb3c0b74bd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home_img_holder']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home_img_holder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8f3b296-2194-46a8-8641-e3c226f793b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dIvsgl cahSX imdb-header__logo-link</value>
      <webElementGuid>dafd5321-795b-4b8d-9dd0-8fb3425dcdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home_img_holder</value>
      <webElementGuid>9dbc26d4-b17f-4e8e-b956-802518e4247f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/?ref_=nv_home</value>
      <webElementGuid>53eeb51b-7777-4ded-a45e-6db466ce89f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>4ebe5306-0c5f-4aa1-a933-2a16da014327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home_img_holder&quot;)</value>
      <webElementGuid>733e9135-22e5-44a4-8bf2-204209690e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='home_img_holder']</value>
      <webElementGuid>0e53b316-b291-4fed-ad3b-aa687eb38411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='imdbHeader']/div[2]/a</value>
      <webElementGuid>bbea0fb3-89b3-4999-9067-790dfe5a9bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/?ref_=nv_home')])[3]</value>
      <webElementGuid>4f4ae24f-baac-4d98-91d1-1959afb41971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>32303a73-af8e-4249-83c7-b95925b1bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'home_img_holder' and @href = '/?ref_=nv_home']</value>
      <webElementGuid>65ba4d7e-9bd5-42a5-aa0c-0f3cac53fce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
