<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Advanced Search_ipc-icon ipc-icon--magnify</name>
   <tag></tag>
   <elementGuidId>0c8dedbc-4f77-42b4-aa9b-e532bfec6c15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.ipc-icon.ipc-icon--magnify</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8df89a11-f095-4078-aeaf-3fb1ec6f6b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1189772f-74d6-4382-80ca-768ed1e3cb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>04c1ddf0-89d3-4889-94c9-a55f033aaa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>813ab71a-30c6-46d9-977f-46278d2bd231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-icon ipc-icon--magnify</value>
      <webElementGuid>4df4b409-736a-4544-b3e5-9c2e49860200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>4247b19e-3133-4db0-aa62-27ab50fb6ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>623e6309-e280-4cdd-a099-010b8b9dcb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5ca73612-9ea8-4aa3-b95b-280f76869afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestion-search-button&quot;)/svg[@class=&quot;ipc-icon ipc-icon--magnify&quot;]</value>
      <webElementGuid>45a4cfa6-fb21-4dd5-8cfd-4b136dca0cd8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
