<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Account Opened</name>
   <tag></tag>
   <elementGuidId>b133ef41-a883-4827-bbb7-6435a2104670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rightPanel']/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c4d8a785-b7ac-4d07-820a-9bfd21ea9fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>223b02fa-9aec-4110-a1d8-8afc8a27b310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Opened!</value>
      <webElementGuid>a8c267a2-a160-4ddc-9738-c5c3fdd04d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>7fd2fa8f-642d-437c-8f31-3d76c9ff1a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/h1</value>
      <webElementGuid>15668129-3249-43ed-a618-bc7d30087df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::h1[1]</value>
      <webElementGuid>9d00bd2e-4b66-4c92-8240-229731ac361d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Loan'])[1]/following::h1[1]</value>
      <webElementGuid>47e424f6-8d73-4d19-9d9a-8d3195050fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your new account number:'])[1]/preceding::h1[1]</value>
      <webElementGuid>ff93f03c-4da2-4d98-b651-1b30a424a5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Account Opened!']/parent::*</value>
      <webElementGuid>2135cabf-1459-42a2-9874-8169beb334ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7b611dea-a1b5-4b2a-a186-7c1bd8f55cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Account Opened!' or . = 'Account Opened!')]</value>
      <webElementGuid>b4473f2c-cd1f-4ebe-b2a4-e1638dfb0b5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
