<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo</name>
   <tag></tag>
   <elementGuidId>20148cd4-3a14-4a28-910a-8858e4ef5bf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topPanel']/a[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec9ed0e5-f75b-4c38-b123-01b14a14781c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/parabank/images/logo.gif;jsessionid=B84B1F706182CD70E05D2C2ABB295AC7</value>
      <webElementGuid>53442080-48b9-4320-9a0a-eb74144bff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ParaBank</value>
      <webElementGuid>47853eb0-8da4-4a63-8bc6-2f3f3379be8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>136</value>
      <webElementGuid>b26bb839-0e6c-4fb8-a792-c0fe5a814017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>da6d310f-5153-4e74-a985-955fcbd6125f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66a4d374-86fb-4d64-9b1f-240241d0e9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>56e0c457-f896-4136-b0dd-c0b8ba3dafb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ParaBank</value>
      <webElementGuid>f9c6fe8f-29bf-46b5-9bd8-14b8db7ff1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topPanel&quot;)/a[2]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>8a07ecb1-d641-4153-a7d2-4af67db9cb26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topPanel']/a[2]/img</value>
      <webElementGuid>81fa4dd7-2cc6-4d89-b125-612b11ae0c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ParaBank']</value>
      <webElementGuid>bd6ff156-7b77-4391-820a-1145deabd3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>8dcfb981-3041-4d29-9f69-40fabd7f059a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/parabank/images/logo.gif;jsessionid=B84B1F706182CD70E05D2C2ABB295AC7' and @alt = 'ParaBank' and @title = 'ParaBank']</value>
      <webElementGuid>920a9050-b2c2-4cb2-ae54-93181cc04f56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
