<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Experience the difference</name>
   <tag></tag>
   <elementGuidId>0d8e0307-f885-4565-a26b-75c5bdfd594e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.caption</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topPanel']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6f716296-044c-49ed-a7ce-1f225a35ef4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>d769f128-8330-492c-bfdb-1f7d2b57740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experience the difference</value>
      <webElementGuid>cab36514-a8c0-4b7c-8f31-faa801404597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topPanel&quot;)/p[@class=&quot;caption&quot;]</value>
      <webElementGuid>f9d7ed9a-69f4-45bd-ba3c-1b46eeb68991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topPanel']/p</value>
      <webElementGuid>dfffdf87-2114-41a5-b02a-bfcee113d9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/preceding::p[1]</value>
      <webElementGuid>e6d8871e-7fc7-4fa6-9e23-8802a1debc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::p[1]</value>
      <webElementGuid>ef071c74-d4ac-4467-be06-13b8dd0e976b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Experience the difference']/parent::*</value>
      <webElementGuid>be79e4d3-b468-430b-9548-ea82180cb891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>cbe2a5a5-d2b0-4661-9ab6-486fa8956e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Experience the difference' or . = 'Experience the difference')]</value>
      <webElementGuid>08e781d0-ef48-4d29-9e53-945b502cebf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
