<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Software_search</name>
   <tag></tag>
   <elementGuidId>1248dccd-3a32-44eb-9f84-790b040e88ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>059ce9d4-2698-4026-bc3a-ca9aec373224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed7e4d5e-8534-4d6f-8ba8-98663138d742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>589a9510-f524-4c91-a63f-5fd31e5c4b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>31e6d0bc-d2ca-4d5d-85ca-bd898a5aa81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autocomplete_route</name>
      <type>Main</type>
      <value>extension/maza/product/product/autocomplete</value>
      <webElementGuid>4d0906f3-c191-4532-a0ef-9528eb614550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search For Products</value>
      <webElementGuid>6d9cb054-c2ed-42f7-a7a0-293057b1af21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search For Products</value>
      <webElementGuid>eb75e250-eb68-4bb1-b06d-958059501fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>953851f6-6925-4cf5-847f-b2a82be3cbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_217822&quot;)/div[@class=&quot;search-wrapper&quot;]/form[1]/div[@id=&quot;search&quot;]/div[@class=&quot;search-input-group flex-fill&quot;]/div[@class=&quot;search-input d-flex&quot;]/div[@class=&quot;flex-fill&quot;]/input[1]</value>
      <webElementGuid>3e79f948-5d36-4888-a3a5-6867f8612089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search']</value>
      <webElementGuid>2c1b60a9-0b44-4395-b44c-66d9a6f49776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div[2]/input</value>
      <webElementGuid>e56a0e4c-48f0-4a5e-8df6-a707fb15f800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d658d99f-5916-44ba-ab17-7e63c50c7bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @placeholder = 'Search For Products']</value>
      <webElementGuid>772f67da-6b46-42fc-a65c-65abeb8441d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
