<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo</name>
   <tag></tag>
   <elementGuidId>22c740f6-0794-4a80-af2f-dd5160e80b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.figure-img.img-fluid.m-0.default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='entry_217821']/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f6e0ce5-6cd9-4e28-ad8b-c7518179ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ecommerce-playground.lambdatest.io/image/catalog/maza/svg/image2vector.svg</value>
      <webElementGuid>97caea02-9b81-4f72-8bce-cb24b8133cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Poco Electro</value>
      <webElementGuid>5127b37c-d0f7-40fb-a175-b4d50567457c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>151</value>
      <webElementGuid>c5ee1b1c-245c-43c9-a397-d4a8f48c1af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1da10189-2110-4c70-99d3-e222f6e5cad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>figure-img img-fluid m-0 default</value>
      <webElementGuid>4f1708fc-74c3-4bae-bd06-c515706de28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entry_217821&quot;)/figure[@class=&quot;figure&quot;]/a[1]/img[@class=&quot;figure-img img-fluid m-0 default&quot;]</value>
      <webElementGuid>1c51b281-93f9-4074-9a24-8a5aad188623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='entry_217821']/figure/a/img</value>
      <webElementGuid>125ee6cc-cfd8-4d5d-8cb2-601dd4b6c5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Poco Electro']</value>
      <webElementGuid>917422df-8e7b-4bde-bc56-92cac79c6f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5a1e1c60-bd89-4c81-804a-1d38559a9e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ecommerce-playground.lambdatest.io/image/catalog/maza/svg/image2vector.svg' and @alt = 'Poco Electro']</value>
      <webElementGuid>86162b83-b4c2-43b9-9ef1-186d9650535c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
