<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu Hamburger</name>
   <tag></tag>
   <elementGuidId>55d1ec6b-da55-4273-9f2a-e2da5aee9339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='imdbHeader-navDrawerOpen']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ipc-responsive-button__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>741ef07a-dda9-494b-9982-17ba5d4561b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipc-responsive-button__text</value>
      <webElementGuid>5c93b43e-87a8-467c-ac6a-9a2b6697dd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>ae136724-e685-4487-87c5-d37911b8f660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader-navDrawerOpen&quot;)/span[@class=&quot;ipc-responsive-button__text&quot;]</value>
      <webElementGuid>170ec7c1-7d21-4540-be3a-7fbfabb9222e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='imdbHeader-navDrawerOpen']/span</value>
      <webElementGuid>f590f2fa-5d92-4688-a85e-921f347bc94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movies'])[1]/preceding::span[2]</value>
      <webElementGuid>011db832-f4a6-4619-944b-4a2617edec7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Calendar'])[1]/preceding::span[4]</value>
      <webElementGuid>b1e701c5-e1c7-495d-9b2e-82b6c069f0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>bc3cfd5f-8fa2-4e9b-bc7f-508a570e8b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>a30592f8-41e4-4107-94ee-de264f1b66ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>37c30941-2060-44bb-ba2d-1b6781be7e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
