<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_MoviesRelease</name>
   <tag></tag>
   <elementGuidId>5635e3d9-75e0-4682-a67a-3de0d4a0d07c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='imdbHeader']/div[2]/aside/div/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navlinkcat__targetWrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd2fe9a4-7127-411b-911c-7bec6b8bf61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navlinkcat__targetWrapper</value>
      <webElementGuid>b9e22f1e-5464-4522-992a-404fb3422e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MoviesRelease CalendarTop 250 MoviesMost Popular MoviesBrowse Movies by GenreTop Box OfficeShowtimes &amp; TicketsMovie NewsIndia Movie Spotlight</value>
      <webElementGuid>4ad1006e-98a8-4781-8299-b1a287d3cad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader&quot;)/div[@class=&quot;ipc-page-content-container ipc-page-content-container--center navbar__inner&quot;]/aside[@class=&quot;sc-kLokBR hhgGKY drawer hamburger__drawer imdb-header__nav-drawer&quot;]/div[@class=&quot;drawer__panel&quot;]/div[@class=&quot;drawer__panelContent&quot;]/div[@class=&quot;sc-bBjSGg lEdew navlcl&quot;]/div[@class=&quot;sc-efHYhv kIOZLn navlinkcat&quot;]/span[@class=&quot;navlinkcat__targetWrapper&quot;]</value>
      <webElementGuid>bc189cf8-c4c3-42fd-b79d-8e2f12954f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='imdbHeader']/div[2]/aside/div/div[2]/div/div/span</value>
      <webElementGuid>754caf6f-a30f-42d8-8fec-9109ec636739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/following::span[1]</value>
      <webElementGuid>71568ac4-03a8-4990-8110-48b1958ae49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>4c4536e5-a893-45ff-9aa2-04439ccfb342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'MoviesRelease CalendarTop 250 MoviesMost Popular MoviesBrowse Movies by GenreTop Box OfficeShowtimes &amp; TicketsMovie NewsIndia Movie Spotlight' or . = 'MoviesRelease CalendarTop 250 MoviesMost Popular MoviesBrowse Movies by GenreTop Box OfficeShowtimes &amp; TicketsMovie NewsIndia Movie Spotlight')]</value>
      <webElementGuid>409c9508-91c4-4e6e-bd2b-c572db3ada8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
